// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcfpzudqcpagjwbqnrvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZnB6dWRxY3BhZ2p3YnFucnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4OTcxNjYsImV4cCI6MjA0OTQ3MzE2Nn0.m4ZUK_VVEGjzeGrv3OkjPN2jOD6UVAx6DpU5_eGpzec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);